spring.datasource:
  plarform: h2
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
# driverClassName: com.mysql.jdbc.Driver
# url: jdbc:mysql://localhost:3306/abt_rails
  username: sa
  password:
  initialize: true # classpath:/schema.sql, import.sql, data.sql
#  validationQuery: SELECT 1
#  maxActive: 10
#  testOnBorrow: true
#  testOnReturn: false

  ## Pool Info ##
  maxActive: 100
  initialSize: 20
  minIdle: 20
  validationQuery: select 1
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 5000 #5 second
  minEvictableIdleTimeMillis: 10000   #10 second
  validationQueryTimeout: 5

# DB - JPA
spring.jpa:
  database: MYSQL
  show-sql: true
  properties.hibernate.hbm2ddl.auto: create # create, update, none, validate
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true